 
import Sidebar from "./assets/components/sidebar/sidebar"
import Navbar from "./assets/components/Navbar/Navbar"
 

import '@/public/assets/css/bootstrap.min.css'
import '@/public/assets/fontawesome/css/all.css'
import '@/public/assets/css/style.css'
import AdminContextContainer from "./assets/context/adminLayoutContext"

 
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
  
    <html lang="en">
    
    
     
    {children}
   
    <Sidebar/>
    <Navbar/>
     
   
     
     
  </html>
    
    
  )
}
